services:
  - type: web
    name: storyhub-front
    env: node
    buildCommand: npm install -g yarn@4.5.0 && yarn install && yarn build
    startCommand: yarn preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 